// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcdoebddgkwxgcexuhrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjZG9lYmRkZ2t3eGdjZXh1aHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNTc1NzksImV4cCI6MjA5MDYzMzU3OX0.aYl_SgTdik_qLEPOepR_GO4DIxlevu58G0FIupPeoQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});